version: "3.7"
services:
  webapp:
    image: ghcr.io/myspeedpuzzling/scraper:master
    volumes:
          - .:/output
    ports:
            - "8080:8080"
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      RUNMODE": "48:00:00"
      STORETYPE: "json"
      RESULTOUTPUTFOLDER: "/output"
      PARSETYPES: "Competition"
      LOGGING__LOGLEVEL__DEFAULT: Information